import { MOCK_EDITORS } from "@/entities/editor/@x/book";
import type { Book } from "./book";

export const MOCK_BOOKS: Book[] = [
  // ---- ACQUISITION ----
  {
    id: "MS-2041",
    title: "The Cartographer's Index",
    author: "Inés Marchetti",
    status: "acquisition",
    position: 0,
    genre: "Literary Fiction",
    wordCount: 92400,
    chapters: 24,
    submitted: "2026-05-11",
    deadline: "2026-06-02",
    progress: 8,
    flag: "review",
    note: "Acquisition committee pending.",
    editor: MOCK_EDITORS.mr,
  },
  {
    id: "MS-2049",
    title: "Saltwater Atlas",
    author: "Daniel Okafor",
    status: "acquisition",
    position: 1,
    genre: "Essays",
    wordCount: 64200,
    chapters: 18,
    submitted: "2026-05-14",
    deadline: "2026-06-09",
    progress: 4,
    note: "First read scheduled.",
    editor: MOCK_EDITORS.pn,
  },
  {
    id: "MS-2052",
    title: "A Field Guide to Forgetting",
    author: "Ruth Bellweather",
    status: "acquisition",
    position: 2,
    genre: "Memoir",
    wordCount: 71800,
    chapters: 22,
    submitted: "2026-05-15",
    deadline: "2026-06-14",
    progress: 12,
    note: "Sample pages with reader.",
    editor: MOCK_EDITORS.ah,
  },

  // ---- DEVELOPMENTAL EDIT ----
  {
    id: "MS-1987",
    title: "Northing & Easting",
    author: "Per Lindqvist",
    status: "developmental",
    position: 0,
    genre: "Historical Fiction",
    wordCount: 118500,
    chapters: 31,
    submitted: "2026-04-02",
    deadline: "2026-05-28",
    progress: 42,
    flag: "urgent",
    note: "Act II restructure in progress.",
    editor: MOCK_EDITORS.ks,
  },
  {
    id: "MS-2003",
    title: "The Hours Between Tides",
    author: "Marisol Vega",
    status: "developmental",
    position: 1,
    genre: "Literary Fiction",
    wordCount: 86300,
    chapters: 27,
    submitted: "2026-04-09",
    deadline: "2026-06-18",
    progress: 38,
    note: "Awaiting author response — round 2 notes.",
    editor: MOCK_EDITORS.mr,
  },
  {
    id: "MS-2017",
    title: "Quiet Apparatus",
    author: "T. Halvorsen",
    status: "developmental",
    position: 2,
    genre: "Science",
    wordCount: 102100,
    chapters: 14,
    submitted: "2026-04-18",
    deadline: "2026-07-03",
    progress: 55,
    note: "Chapter 6 revision returned.",
    editor: MOCK_EDITORS.jt,
  },

  // ---- COPY EDIT ----
  {
    id: "MS-1942",
    title: "Stoneware",
    author: "Yusuf Demir",
    status: "copyedit",
    position: 0,
    genre: "Short Stories",
    wordCount: 58900,
    chapters: 12,
    submitted: "2026-03-14",
    deadline: "2026-05-22",
    progress: 64,
    flag: "urgent",
    note: "Style sheet locked.",
    editor: MOCK_EDITORS.el,
  },
  {
    id: "MS-1955",
    title: "Lantern Practice",
    author: "Wren Ahmadi",
    status: "copyedit",
    position: 1,
    genre: "Poetry",
    wordCount: 21400,
    chapters: 6,
    submitted: "2026-03-21",
    deadline: "2026-06-06",
    progress: 71,
    note: "Italics pass complete.",
    editor: MOCK_EDITORS.ah,
  },

  // ---- DESIGN & TYPESETTING ----
  {
    id: "MS-1908",
    title: "Vellum & Wire",
    author: "Camille Brouchard",
    status: "design",
    position: 0,
    genre: "Art History",
    wordCount: 134700,
    chapters: 9,
    submitted: "2026-02-28",
    deadline: "2026-06-11",
    progress: 78,
    note: "Plate section v3 with designer.",
    editor: MOCK_EDITORS.ks,
  },
  {
    id: "MS-1922",
    title: "The Empty Quarter",
    author: "Idris al-Mansouri",
    status: "design",
    position: 1,
    genre: "Travel",
    wordCount: 88600,
    chapters: 21,
    submitted: "2026-03-03",
    deadline: "2026-05-30",
    progress: 82,
    flag: "urgent",
    note: "Cover R3 — awaiting sign-off.",
    editor: MOCK_EDITORS.pn,
  },

  // ---- FINAL PROOF ----
  {
    id: "MS-1871",
    title: "A Catalogue of Small Disasters",
    author: "Ottilie Karsten",
    status: "proof",
    position: 0,
    genre: "Literary Fiction",
    wordCount: 79200,
    chapters: 28,
    submitted: "2026-01-22",
    deadline: "2026-05-24",
    progress: 91,
    flag: "urgent",
    note: "Page proofs with author.",
    editor: MOCK_EDITORS.mr,
  },
  {
    id: "MS-1885",
    title: "Eight Bridges",
    author: "Hiroshi Maeda",
    status: "proof",
    position: 1,
    genre: "Literary Fiction",
    wordCount: 96100,
    chapters: 19,
    submitted: "2026-02-04",
    deadline: "2026-06-04",
    progress: 88,
    note: "Final read returned clean.",
    editor: MOCK_EDITORS.jt,
  },

  // ---- TO PRESS ----
  {
    id: "MS-1820",
    title: "The Quiet Stations",
    author: "Eleanor Pryce",
    status: "press",
    position: 0,
    genre: "Memoir",
    wordCount: 68400,
    chapters: 16,
    submitted: "2025-12-18",
    deadline: "2026-05-20",
    progress: 100,
    note: "Files transmitted — 04:12 UTC.",
    editor: MOCK_EDITORS.el,
  },
  {
    id: "MS-1832",
    title: "Birds, Believing",
    author: "Tomás Reyes-Vela",
    status: "press",
    position: 1,
    genre: "Poetry",
    wordCount: 19800,
    chapters: 5,
    submitted: "2026-01-04",
    deadline: "2026-05-21",
    progress: 100,
    note: "Print run: 4,000 hardcover.",
    editor: MOCK_EDITORS.ah,
  },
];
